local_resinos:
  app-name: envirophat
  build-triggers:
    - Dockerfile: bc808f7597edee274123179fcdee86d23a5f3f13d651950888f1cc05517353a7
    - requirements.txt: de53e9c9257cab57735040ef3aad820621fe05bd3f3fa42c44edcae473f56caf
  environment:
    - RESIN_vars=There Are None for resinOS Unmanaged
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
  - Dockerfile
